# Лабораторная работа 7. Управление ресурсами в однопроцессорной с неоднородными заявками, аппроксимация немарковских процессов потоками Эрланга.

## Задание 1.

В однопроцессорную  систему случайным образом поступают на выполнение $m$ разных типов программ, отличающихся известной трудоемкостью $Q_1, Q_2, \ldots, Q_m$. Входящий поток простейший с интенсивностью $\lambda$.

Представив данную систему как одноканальную СМО с неограниченной очередью, вычислить среднее время обслуживания программ, считая длительность обслуживания случайной величиной (теоретически и экспериментально) - не учитывая известные трудоемкости.

Реализовать алгоритм SPT, выбирая из очереди заявки в соответствии с их приоритетом по трудоемкости. Рассчитать среднее время обслуживания программ. Сравнить полученные результаты.

Реализовать алгоритм RR при заданном кванте времени $q$. Оценить среднее время обслуживания программ. Сравнить полученные результаты. Выяснить, как влияет величина кванта на среднее время обслуживания программ.

In [47]:
Variant<-6
set.seed(Variant+212) 
m<-sample(c(6:20),1)
lambda<-runif(1,0.1, 2)
Q<-rexp(m,0.3)
q<-sample(c(1:4),1)
View(data.frame(m,q, lambda))
print(Q)

  m  q lambda
1 10 4 1.88152

 [1] 2.5018515 4.0450762 2.0498893 1.1775382 7.0369009 0.9571518 0.2200340
 [8] 1.7995447 2.3890709 0.1193048

## Задание 2.

На $N$ серверов с ограничением на длину очереди $M$ поступает поток заявок с заданным законом распределения, поток обслуживания также подчиняется заданному закону распределения. 

Принятые обозначения:

$M$ - экспоненциальное распределение;

$E_2$ - распределение Эрланга 2 порядка;

$E_3$ - распределение Эрланга 3 порядка.

Используя:
- метод этапов;
- экспериментальную модель на языке R;
- систему моделирования дискретных событий Simmer в R;

определить:

- среднее время нахождения заявки в системе;
- среднее количество заявок в системе;
- среднее время нахождения заявки в очереди;
- среднюю длину очереди;
- абсолютную пропускную способность системы.

In [15]:
Variant<-5
set.seed(Variant) 
N<-sample(c(2:4),1)
M<-sample(c(2:4),1)
lambda<-runif(1,0.1, 2)
mu <- runif(1,0.1, 2)
choice <-sample(c("E_2","E_3"),1)
IO<-sample(c("input", "output"),1)
if (IO == "input") {input <-choice; output <-"M"} else {input <-"M"; output <-choice}
D<- data.frame(N, M, lambda, mu, input, output )
View(D)

  N M lambda   mu       input output
1 3 4 1.842064 0.640359 E_2   M